TABLE_WIDTH = 2300
TABLE_HEIGHT = 1150
DISTANCE_OF_CAMERA_FROM_CENTER = 60
FORM = 70
ROBOT = 160
SAFETY_RADIUS = 30
BORDER_SECURITY_RADIUS = ROBOT + SAFETY_RADIUS
OBSTACLE_RADIUS_ADJUSTMENT = FORM + ROBOT + SAFETY_RADIUS
